import type { SettingsCategory } from './constants';
import type { OptionsPageProps } from './types';

export interface SearchableItem {
  id: string;
  category: SettingsCategory;
  keywords: string;
}

/** Props for main category pages that support search filtering */
export interface CategoryPageProps extends OptionsPageProps {
  visibleIds: Set<string> | null;
  isSearching: boolean;
}

export const SEARCHABLE_ITEMS: SearchableItem[] = [
  { id: 'fontSize', category: 'editor', keywords: 'font size pixels editor text' },
  { id: 'fontFamily', category: 'editor', keywords: 'font family monospace typeface editor' },
  { id: 'lineNumbers', category: 'editor', keywords: 'line numbers gutter editor' },
  { id: 'readableLineLength', category: 'editor', keywords: 'readable line length max width content narrow editor' },
  { id: 'theme', category: 'appearance', keywords: 'theme catppuccin mocha macchiato frappe latte dark light color' },
  { id: 'vimMode', category: 'editor', keywords: 'vim mode keybindings modal editor' },
  { id: 'tabSize', category: 'editor', keywords: 'tab size indent spaces editor' },
  { id: 'highlightActiveLine', category: 'editor', keywords: 'highlight active line cursor editor' },
  { id: 'defaultViewMode', category: 'editor', keywords: 'default view mode live source reading preview editor' },
  { id: 'spellcheck', category: 'features', keywords: 'spell check spelling editor toggle feature enable disable' },
  { id: 'codeBlockLineNumbers', category: 'editor', keywords: 'code block line numbers fenced preview' },
  { id: 'accentColor', category: 'appearance', keywords: 'accent color highlight theme appearance' },
  { id: 'sidebarPosition', category: 'appearance', keywords: 'sidebar position left right layout appearance' },
  { id: 'uiFontSize', category: 'appearance', keywords: 'ui font size interface text appearance' },
  { id: 'fileSortOrder', category: 'files', keywords: 'sort order name modified files' },
  { id: 'confirmBeforeDelete', category: 'files', keywords: 'confirm delete warning files' },
  { id: 'useTrash', category: 'files', keywords: 'trash delete permanent move files' },
  { id: 'showFileExtensions', category: 'files', keywords: 'file extensions md show hide files' },
  { id: 'showFolderIcons', category: 'files', keywords: 'folder icons show hide sidebar explorer' },
  { id: 'showFileIcons', category: 'files', keywords: 'file icons show hide sidebar explorer' },
  { id: 'folderColorSubfolders', category: 'folder-colors', keywords: 'folder color subfolders inherit children' },
  { id: 'folderColorFiles', category: 'folder-colors', keywords: 'folder color files inherit tint children' },
  { id: 'folderColorIcon', category: 'folder-colors', keywords: 'folder color icon tint' },
  { id: 'folderColorName', category: 'folder-colors', keywords: 'folder color name text label' },
  { id: 'folderColorBackground', category: 'folder-colors', keywords: 'folder color background row highlight tint' },
  { id: 'folderColorChevron', category: 'folder-colors', keywords: 'folder color chevron arrow expand collapse' },
  { id: 'folderColorFileIcon', category: 'folder-colors', keywords: 'file color icon tint inherit' },
  { id: 'folderColorFileName', category: 'folder-colors', keywords: 'file color name text label inherit' },
  { id: 'folderColorFileBackground', category: 'folder-colors', keywords: 'file color background row highlight tint inherit' },
  { id: 'folderColorStyle', category: 'folder-colors', keywords: 'folder color style preset mode icon text background accent dot' },
  { id: 'folderColorFileStyle', category: 'folder-colors', keywords: 'file color style preset mode icon text background accent dot' },
  { id: 'folderColorBold', category: 'folder-colors', keywords: 'folder color bold font weight' },
  { id: 'folderColorOpacity', category: 'folder-colors', keywords: 'folder color opacity intensity transparency' },
  { id: 'templatesFolder', category: 'files', keywords: 'templates folder path directory files new note' },
  { id: 'attachmentLocation', category: 'files', keywords: 'attachment image paste location folder files' },
  { id: 'attachmentsFolder', category: 'files', keywords: 'attachments folder path directory files' },
  { id: 'autoSaveEnabled', category: 'features', keywords: 'auto save enable disable general toggle feature' },
  { id: 'language', category: 'general', keywords: 'language display interface locale general' },
  { id: 'startupBehavior', category: 'general', keywords: 'startup behavior reopen last vault picker general' },
  { id: 'enableFolderColors', category: 'features', keywords: 'folder colors coloring toggle feature enable disable' },
  { id: 'enableWikiLinks', category: 'features', keywords: 'wiki links wikilinks toggle feature enable disable' },
  { id: 'enableLivePreview', category: 'features', keywords: 'live preview toggle feature enable disable decorations' },
  { id: 'enableTags', category: 'features', keywords: 'tags hashtags toggle feature enable disable' },
  { id: 'enableGraphView', category: 'features', keywords: 'graph view toggle feature enable disable network' },
  { id: 'enableBacklinks', category: 'features', keywords: 'backlinks references toggle feature enable disable' },
  { id: 'enableOutline', category: 'features', keywords: 'outline headings toc toggle feature enable disable' },
  { id: 'enableVariables', category: 'features', keywords: 'variables template frontmatter replacement toggle feature enable disable' },
  { id: 'wikilinksOptions', category: 'wikilinks-options' as SettingsCategory, keywords: 'wiki links open new tab full path create follow options' },
  { id: 'livepreviewOptions', category: 'livepreview-options' as SettingsCategory, keywords: 'live preview headings bold italic links images code blocks render options' },
  { id: 'tagsOptions', category: 'tags-options' as SettingsCategory, keywords: 'tags autocomplete nested support hashtags options' },
  { id: 'graphOptions', category: 'graph-options' as SettingsCategory, keywords: 'graph node size link distance orphans max nodes view options' },
  { id: 'backlinksOptions', category: 'backlinks-options' as SettingsCategory, keywords: 'backlinks context lines group folder references options' },
  { id: 'outlineOptions', category: 'outline-options' as SettingsCategory, keywords: 'outline heading level auto expand toc options' },
  { id: 'variablesOptions', category: 'variables-options' as SettingsCategory, keywords: 'variables delimiter separator missing nesting case insensitive array join preserve options' },
  { id: 'enableDailyNotes', category: 'features', keywords: 'daily notes toggle feature enable disable' },
  { id: 'dailynotesOptions', category: 'dailynotes-options' as SettingsCategory, keywords: 'daily notes folder date format template options' },
  { id: 'enableCodeFolding', category: 'features', keywords: 'code folding fold headings collapse toggle feature enable disable' },
  { id: 'enableHighlightSyntax', category: 'features', keywords: 'highlight syntax marker toggle feature enable disable' },
  { id: 'enableProperties', category: 'features', keywords: 'properties frontmatter yaml widget toggle feature enable disable' },
  { id: 'enableStatusBar', category: 'features', keywords: 'status bar word count toggle feature enable disable' },
  { id: 'enableTemplates', category: 'features', keywords: 'templates variables toggle feature enable disable' },
  { id: 'enableSearch', category: 'features', keywords: 'search vault find toggle feature enable disable' },
  { id: 'enableSlashCommands', category: 'features', keywords: 'slash commands menu inline insert toggle feature enable disable' },
  { id: 'enableFocusMode', category: 'features', keywords: 'focus mode zen distraction free toggle feature enable disable' },
  { id: 'enableWordCountGoal', category: 'features', keywords: 'word count goal target writing toggle feature enable disable' },
  { id: 'enableBookmarks', category: 'features', keywords: 'bookmarks favorites star files toggle feature enable disable' },
  { id: 'enableCanvas', category: 'features', keywords: 'canvas whiteboard visual cards nodes edges toggle feature enable disable' },
  { id: 'enableTypewriterMode', category: 'features', keywords: 'typewriter mode cursor center scroll toggle feature enable disable' },
  { id: 'enableIndentGuides', category: 'features', keywords: 'indent guides lines vertical indentation toggle feature enable disable' },
  { id: 'enableImagePreview', category: 'features', keywords: 'image preview inline pictures toggle feature enable disable' },
  { id: 'enableMathPreview', category: 'features', keywords: 'math latex katex equation preview toggle feature enable disable' },
  { id: 'enableCalloutPreview', category: 'features', keywords: 'callout admonition alert note warning preview toggle feature enable disable' },
  { id: 'enableMediaViewer', category: 'features', keywords: 'media viewer image pdf picture toggle feature enable disable' },
  { id: 'enableMermaidPreview', category: 'features', keywords: 'mermaid diagram chart flowchart preview toggle feature enable disable' },
  { id: 'enableQueryPreview', category: 'features', keywords: 'query dataview table list properties filter sort preview toggle feature enable disable' },
  { id: 'enableTableOfContents', category: 'features', keywords: 'table of contents toc headings toggle feature enable disable' },
  { id: 'focusmodeOptions', category: 'focusmode-options' as SettingsCategory, keywords: 'focus mode dim paragraphs typewriter zen options' },
  { id: 'wordcountgoalOptions', category: 'wordcountgoal-options' as SettingsCategory, keywords: 'word count goal target status bar notification options' },
  { id: 'canvasOptions', category: 'canvas-options' as SettingsCategory, keywords: 'canvas whiteboard visual cards nodes edges options' },
  { id: 'bookmarksOptions', category: 'bookmarks-options' as SettingsCategory, keywords: 'bookmarks favorites star files options' },
  { id: 'typewriterOptions', category: 'typewriter-options' as SettingsCategory, keywords: 'typewriter mode offset cursor center scroll options' },
  { id: 'indentguidesOptions', category: 'indentguides-options' as SettingsCategory, keywords: 'indent guides color style solid dashed dotted options' },
  { id: 'imagepreviewOptions', category: 'imagepreview-options' as SettingsCategory, keywords: 'image preview max height inline options' },
  { id: 'mediaviewerOptions', category: 'mediaviewer-options' as SettingsCategory, keywords: 'media viewer pdf image zoom default options' },
  { id: 'tocOptions', category: 'toc-options' as SettingsCategory, keywords: 'table of contents toc auto update save headings options' },
  { id: 'queryOptions', category: 'query-options' as SettingsCategory, keywords: 'query dataview table list properties filter sort from where limit options' },
  { id: 'codefoldingOptions', category: 'codefolding-options' as SettingsCategory, keywords: 'code folding headings code blocks minimum level options' },
  { id: 'highlightOptions', category: 'highlight-options' as SettingsCategory, keywords: 'highlight color marker options' },
  { id: 'propertiesOptions', category: 'properties-options' as SettingsCategory, keywords: 'properties frontmatter show types options' },
  { id: 'statusbarOptions', category: 'statusbar-options' as SettingsCategory, keywords: 'status bar words chars reading time selection options' },
  { id: 'autosaveOptions', category: 'autosave-options' as SettingsCategory, keywords: 'auto save interval delay timer options' },
  { id: 'spellcheckOptions', category: 'spellcheck-options' as SettingsCategory, keywords: 'spell check spelling browser options' },
  { id: 'templatesOptions', category: 'templates-options' as SettingsCategory, keywords: 'templates folder variables cursor clipboard date options' },
  { id: 'searchOptions', category: 'search-options' as SettingsCategory, keywords: 'search case sensitive regex whole word options' },
  { id: 'slashCommandsOptions', category: 'slashcommands-options' as SettingsCategory, keywords: 'slash commands menu inline insert options' },
  { id: 'syncOptions', category: 'sync-options' as SettingsCategory, keywords: 'sync github git repository backup cloud push pull auto-sync interval token' },
  { id: 'syncEnabled', category: 'features', keywords: 'sync github git cloud backup toggle feature enable disable' },
];
